export const ALLOWED_COMMANDS = [
  "buy-credits",
  "help",
  "--version",
  "-v",
  "login",
  "network",
  "balance",
] as const;
export type AllowedCommand = (typeof ALLOWED_COMMANDS)[number];

export const COMMAND_DESCRIPTIONS = {
    "buy-credits": "Purchase credits for Catapulta deployments and operations",
    "help": "Display help information and available commands",
    "--version": "Show the current version of Catapulta CLI",
    "-v": "Show the current version of Catapulta CLI (short form)",
    "login": "Authenticate with Catapulta services",
    "network": "Display information about supported networks and their configurations",
    "balance": "Display the credit balance of your Catapulta account",
  } as const;

export const NETWORKS = [
  "matic",
  "maticMumbai",
  "polygonAmoy",
  "main",
  "arbitrum",
  "arbitrumGoerli",
  "arbitrumSepolia",
  "avalanche",
  "avalancheFuji",
  "optimism",
  "optimismGoerli",
  "optimismSepolia",
  "goerli",
  "sepolia",
  "base",
  "baseTestnet",
  "baseSepolia",
  "bsc",
  "bscTestnet",
  "gnosis",
  "gnosisTestnet",
  "scroll",
  "scrollSepolia",
  "metis",
  "metisTestnet",
  "zksyncEraMainnet",
  "zksyncSepolia",
  "polygonZkEvm",
  "polygonZkEvmTestnet",
  "stavenger",
  "zKatana",
  "blastSepolia",
  "blast",
  "holesky",
  "fantom",
  "fantomTestnet",
  "celo",
  "moonbeam",
  "moonbeamTestnet",
  "kroma",
  "kromaSepolia",
  "mantle",
  "mantleSepolia",
  "zeeveDemo",
  "degen",
  "bartio",
  "sonic",
  "sonicTestnet",
  "lensTestnet",
  "unichainTestnet",
  "mode",
  "modeTestnet",
  "monadTestnet",
  "ink",
  "inkTestnet",
  "corn",
  "cornTestnet",
] as const;

export type Network = (typeof NETWORKS)[number]; 